services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 4318:4318 # OTLP
      - 16686:16686 # UI
      - 14269:14269 # Admin
      - 14268:14268 # Collector
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    network_mode: host

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: host

  notification-service:
    image: chrisncs/notification-service
    ports:
      - "9292:9292"
    environment:
      TRACING_URL: http://localhost:4318/v1/traces
      SNS_TOPIC_ARN: arn:aws:sns:eu-west-1:124355645722:primaryApplication
      AWS_REGION: eu-west-1
    network_mode: host
    depends_on:
      - jaeger

  user-service:
    image: chrisncs/user-service
    ports:
      - "9193:9193"
    environment:
      TRACING_URL: http://localhost:4318/v1/traces
      SPRING_DATASOURCE_HOST_URL: jdbc:postgresql://localhost:5432/tms
      SPRING_DATASOURCE_USERNAME: postgres-user
      SPRING_DATASOURCE_PASSWORD: postgres-pass
      SPRING_KAFKA_BOOTSTRAP_SERVERS: http://localhost:9092
      SERVER_PORT: "9193"
    network_mode: host
    depends_on:
      - jaeger

  task-api:
    image: chrisncs/task-api
    ports:
      - "9191:9191"
    environment:
      SPRING_DATASOURCE_HOST_URL: jdbc:postgresql://localhost:5432/tms
      SPRING_DATASOURCE_USERNAME: postgres-user
      SPRING_DATASOURCE_PASSWORD: postgres-pass
      TRACING_URL: http://localhost:4318/v1/traces
      SERVER_PORT: "9191"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: http://localhost:9092
    network_mode: host
    depends_on:
      - jaeger

networks:
  app-network:
    driver: bridge
