version: "3.8"

services:
  kafka:
    image: apache/kafka:latest
    container_name: ckafka
    user: root
    ports:
      - "9092:9092"
      # Internal controller listener port; not exposed
      - "9093:9093"
    environment:
      # Unique ID for this node in the quorum
      KAFKA_NODE_ID: 1
      # Run both broker and controller in a single process
      KAFKA_PROCESS_ROLES: broker,controller
      # Define controller quorum voters (single-node: 1@<host>:9093)
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      # Bind listeners: client PLAINTEXT on 9092, controller on 9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      # Advertise the client-facing listener
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      # Name of the controller listener
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # Data directory for logs (optional override)
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - ./kafka_data:/var/lib/kafka/data

volumes:
  kafka_data:
    driver: local
